apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: clickstream
spec:
  replicas: 1            # Online learning için TEK writer
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: clickstream-spark:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: clickstream-config
        env:
        - name: JAVA_HOME
          value: /opt/java
        - name: PYSPARK_GATEWAY_TIMEOUT
          value: "300"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 3Gi